    1. seperti biasa kita mengimport library yang dibutuhkan untuk dataset kita .yang pertama ada pandas yang berfungsi untuk membaca file.csv kita pada dataset. dan yang kedua di sini kita membutuhkan library dari sci-kit learn untuk melakukan pembagian pada dataset baik itu untuk menguji model maupun untuk melatih model dataset.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

    2. saya menggunakan nama variable pertama yaitu df dimana di dalam df itu saya memanggil library pandas untuk membaca file.csv saya dengan pd.rad_csv. dan saya menampilkan filenya dengan df untuk melihat struktur data kita dalam dataset.

In [2]:
df = pd.read_csv('IndianWeatherRepository.csv')
df.head( 20)

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,waktu_hari
0,India,Ashoknagar,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,18.5,1,2,05:59 AM,06:41 PM,05:42 PM,03:38 AM,Waxing Gibbous,93,siang
1,India,Raisen,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,14.2,1,1,06:00 AM,06:40 PM,05:39 PM,03:41 AM,Waxing Gibbous,93,malam
2,India,Chhindwara,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,2023-08-29 10:45,26.3,79.3,...,20.7,2,2,05:56 AM,06:34 PM,05:32 PM,03:39 AM,Waxing Gibbous,93,siang
3,India,Betul,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,2023-08-29 10:45,25.6,78.1,...,6.6,1,1,06:00 AM,06:38 PM,05:36 PM,03:43 AM,Waxing Gibbous,93,siang
4,India,Hoshangabad,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.2,81.0,...,14.8,1,1,06:01 AM,06:39 PM,05:38 PM,03:42 AM,Waxing Gibbous,93,siang
5,India,Sehore,Madhya Pradesh,23.20,77.08,Asia/Kolkata,1693286100,2023-08-29 10:45,25.9,78.6,...,10.5,1,1,06:03 AM,06:42 PM,05:42 PM,03:44 AM,Waxing Gibbous,93,malam
6,India,Jabalpur,Madhya Pradesh,23.17,79.95,Asia/Kolkata,1693286100,2023-08-29 10:45,28.0,82.4,...,23.1,2,2,05:51 AM,06:31 PM,05:30 PM,03:32 AM,Waxing Gibbous,93,malam
7,India,Narsimhapur,Madhya Pradesh,22.95,79.20,Asia/Kolkata,1693286100,2023-08-29 10:45,27.7,81.9,...,23.7,2,2,05:55 AM,06:34 PM,05:33 PM,03:36 AM,Waxing Gibbous,93,siang
8,India,Panna,Madhya Pradesh,24.72,80.20,Asia/Kolkata,1693286100,2023-08-29 10:45,30.0,86.0,...,35.5,2,3,05:49 AM,06:31 PM,05:32 PM,03:27 AM,Waxing Gibbous,93,malam
9,India,Ujjain,Madhya Pradesh,23.18,75.77,Asia/Kolkata,1693286100,2023-08-29 10:45,26.0,78.8,...,7.6,1,1,06:08 AM,06:48 PM,05:47 PM,03:49 AM,Waxing Gibbous,93,siang
10,India,Rewa,Madhya Pradesh,24.53,81.30,Asia/Kolkata,1693286100,2023-08-29 10:45,30.6,87.1,...,26.8,2,2,05:45 AM,06:26 PM,05:27 PM,03:23 AM,Waxing Gibbous,93,siang
11,India,Dindori,Madhya Pradesh,22.95,81.08,Asia/Kolkata,1693286100,2023-08-29 10:45,30.3,86.5,...,15.6,1,2,05:47 AM,06:26 PM,05:25 PM,03:28 AM,Waxing Gibbous,93,malam
12,India,Balaghat,Madhya Pradesh,21.78,80.25,Asia/Kolkata,1693286100,2023-08-29 10:45,28.3,82.9,...,20.7,2,2,05:51 AM,06:28 PM,05:26 PM,03:34 AM,Waxing Gibbous,93,siang
13,India,Barwani,Madhya Pradesh,22.03,74.90,Asia/Kolkata,1693286100,2023-08-29 10:45,27.2,81.0,...,8.2,1,1,06:12 AM,06:50 PM,05:49 PM,03:55 AM,Waxing Gibbous,93,siang
14,India,Satna,Madhya Pradesh,24.58,80.83,Asia/Kolkata,1693286100,2023-08-29 10:45,30.1,86.2,...,24.2,2,2,05:47 AM,06:28 PM,05:29 PM,03:25 AM,Waxing Gibbous,93,siang
15,India,Chhatarpur,Madhya Pradesh,24.90,79.60,Asia/Kolkata,1693286100,2023-08-29 10:45,30.0,86.0,...,35.5,2,3,05:51 AM,06:34 PM,05:35 PM,03:29 AM,Waxing Gibbous,93,siang
16,India,Indore,Madhya Pradesh,22.72,75.83,Asia/Kolkata,1693286100,2023-08-29 10:45,26.0,78.8,...,8.0,1,1,06:08 AM,06:47 PM,05:46 PM,03:50 AM,Waxing Gibbous,93,siang
17,India,Ratlam,Madhya Pradesh,23.32,75.07,Asia/Kolkata,1693286100,2023-08-29 10:45,26.5,79.7,...,10.8,1,1,06:10 AM,06:51 PM,05:50 PM,03:52 AM,Waxing Gibbous,93,siang
18,India,Harda,Madhya Pradesh,22.33,77.10,Asia/Kolkata,1693286100,2023-08-29 10:45,28.4,83.1,...,9.4,1,1,06:03 AM,06:42 PM,05:40 PM,03:46 AM,Waxing Gibbous,93,malam
19,India,Sagar,Madhya Pradesh,23.83,78.72,Asia/Kolkata,1693286100,2023-08-29 10:45,26.9,80.4,...,25.5,2,2,05:56 AM,06:36 PM,05:36 PM,03:36 AM,Waxing Gibbous,93,malam

    3. disini kita menggunakan fungsi 'iloc' dimana X = df.iloc[:,:-1] kita mengambil semua kolom kecuali kolom terakhir dalam dataframe 'df' untuk melakukan uji model pada dataset kita dan mengatribusikannya kedalam variable x. dan y = df.iloc[:,-1] kita mengambil semua baris pada dataframe 'df' tetapi hanya kolom terakhir dan akan kita jadikan target dan mengatribusikannya kedalam variable y.

In [3]:
X = df.iloc[:,:-1] 
y = df.iloc[:,-1]

    4. kita melakukan psemisahan data baik untuk melakukan uji model dan melakukan tes kinerja model pada dataset dimana X_train degunakan untuk melatih model, X_test degunakan untuk menguji kinerja model,y_train digunakan untuk melatih model dan y_test digunakan untuk melatih kinerja model. test_size=0.3 berfungsi untuk melakukan pembagian pada kinerja yang akan diuji dimana 0.3 yang berarti 30% akan digunakan untuk melatih kinerja model atau test set.

In [4]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

    5. pertama kita mencetak dimensi dari X_train, yaitu jumlah baris (instances) dan kolom (fitur) pada subset fitur yang akan digunakan untuk melatih model. selanjutnya kita mencetak dimensi dari X_test, yaitu jumlah baris (instances) dan kolom (fitur) pada subset fitur yang akan digunakan untuk menguji kinerja model. lalu kita mencetak dimensi dari y_train, yaitu jumlah elemen (target) pada subset target yang akan digunakan untuk melatih model.dan yang terakhir kita mencetak dimensi dari y_test, yaitu jumlah elemen (target) pada subset target yang akan digunakan untuk menguji kinerja model.dimana funsi shape adalah melakukan perhitungan pada dataframe 'df'.

In [5]:
print("Dimensi X train : ", X_train.shape)
print("Dimensi X test : ", X_test.shape)
print("Dimensi y train : ", y_train.shape)
print("Dimensi y test : ", y_test.shape)

Dimensi X train :  (12257, 42)
Dimensi X test :  (5254, 42)
Dimensi y train :  (12257,)
Dimensi y test :  (5254,)

### Normalisasi

    6. kita mengimport library yang diinginkan terlebiuh dahulu untuk melakukan normalisasi pada data dengan minMax dan sekalian kita mengimport library untuk melakukan standarisasi pada data kita. dan mengimport numpy untuk melakukan manipulasi array multidimensi atau perhitungan matematika.

In [6]:
from sklearn.preprocessing import MinMaxScaler , StandardScaler
import numpy as np

    7. perintah yang diberikan yaitu melakukan copy pada data kita terlebih dahulu maka kita perlu menambahkan variable baru untuk melakukan copy data kita dan menggunakan fungsi 'copy()'.

In [7]:
df_copy = df.copy()

    8.  a) dalam variable bernama 'data' saya memiliki asrray yang mengkonversi input kedalam numpy.dalam hal ini adalah arrya yang memiliki 4 baris dan 2 kolom dta. sebelum melanjutkan terlebih dahulu melakukan copy data agar data utama tidak akan terpengaruh oleh modifikasi yang akan kita lakukan tersebut dengan cara menggunakan fungsi 'copy()'.

    b) dalam data yang belum di normalisasi kita memanggil data yang telah kita copy agar data utama kita tidak terpengaruh dan variable yang menampung hasil salinan adalah 'data_copy'. dan untuk menghitung standar deviasinya kita menggunakan fungsi 'std' yang berfungsi untuk menghitung standar deviasi dari rata-rata suatu nilai,jika standar deviasinya semakin besar berarti data cenderung lebih tersebar sedangkan jika nilai standar deviasinya semakin rendah berarti nilai-nilai dalam dataset cenderung lebih dekat dengan rata-rata.

    c) seblum melakukan normalisasi kita terlebuh dahulu melakukan pendefinisian fungsi 'scaler = MinMaxScaler()'. dimana normalisasi ini dilakukan pada data yang telah di salin terlebih dahulu.dan pada fungsi 'print' memanggil 'scaler_data' yang menampung perhitungan normalisasi data yang telah di salin sebelumnya begitu juga halnya standar deviasinya. dan perlu diingat bahwa Normalisasi adalah teknik perubahan skala pada data yang memiliki dimensi berbeda-beda menjadi [0, 1].

In [8]:
data = np.asarray([[100, 0.001],
                    [8, 0.05],
                    [50, 0.005],
                    [88, 0.07],])
data_copy = data.copy()

print("Nilai Data Sebelum Normalisasi:")
print(data_copy)
print("Nilai standar deviasi sebelum Normaslisasi:", np.std(data_copy))

scaler = MinMaxScaler()
Scaler_data = scaler.fit_transform(data_copy)

print("\nNilai Data setelah Normalisasi:")
print(Scaler_data)
print("Nilai standar deviasi setelah Normalisasi:", np.std(Scaler_data))

Nilai Data Sebelum Normalisasi:
[[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]]
Nilai standar deviasi sebelum Normaslisasi: 39.89949316955668

Nilai Data setelah Normalisasi:
[[1.         0.        ]
 [0.         0.71014493]
 [0.45652174 0.05797101]
 [0.86956522 1.        ]]
Nilai standar deviasi setelah Normalisasi: 0.4148659497972776

### Standarisasi

    10. kita melakukan hal yang sama pada saat melakukan normalisasi diatas hanya saja fungsi yang kita gunakan berbeda yaitu menggunakan 'StandardScaler()' yang disimpan dalam variable 'scaler2', dan memanggil variable 'Scaler_data2' yang telah menampung perhitungan standarisasi dalam data yang telah kita salin. dan perlu diingat bahwa standarisasi adalah proses penskalaan data sehingga memiliki nilai rata-rata 0 dan standar deviasi 1. jadi standar deviasinya berubah menjadi 1

In [9]:
data2 = np.asarray([[100, 0.01],
                    [8, 0.05],
                    [66, 0.05],
                    [99, 0.07],])


data_copy2 = data2.copy()

print("Nilai Data Sebelum scaling:")
print(data_copy2)
print("Nilai standar deviasi sebelum scaling:", np.std(data_copy2))

scaler2 = StandardScaler()


Scaler_data2 = scaler2.fit_transform(data_copy2)

print("\nNilai Data setelah scaling:")
print(Scaler_data2)
print("Nilai standar deviasi setelah scaling:", np.std(Scaler_data2))

Nilai Data Sebelum scaling:
[[1.0e+02 1.0e-02]
 [8.0e+00 5.0e-02]
 [6.6e+01 5.0e-02]
 [9.9e+01 7.0e-02]]
Nilai standar deviasi sebelum scaling: 43.14596729417478

Nilai Data setelah scaling:
[[ 0.84940807 -1.60591014]
 [-1.61186886  0.22941573]
 [-0.06019427  0.22941573]
 [ 0.82265506  1.14707867]]
Nilai standar deviasi setelah scaling: 1.0

### Data Cleaning Nilai Null

    11. untuk dapat menggunakan menjalankan data cleaning kita terlebih dahulu mengimport bebera library yang diperlukan dengan 'from sklearn.impute import SimpleImputer'

In [10]:
from sklearn.impute import SimpleImputer

    12. untuk melkukan data cleaning pada variable dengan nilai null terlebih dahulu kita mengecheck apakan dataset kita mempunya variable dengan nilai null dengan menggunakan perintah 'print(df.isna().sum())' dan hasilnya dataset kita tidak memiliki nilai null saperti yang terlihat dibawah ini.

In [11]:
print("Jumlah record yang memiliki nilai null:")
print(df.isna().sum())

Jumlah record yang memiliki nilai null:
country                         0
location_name                   0
region                          0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
waktu_hari                      0
dtype: int64

    13. pada perintah dibawah saya ingin mencari atribut yang memiliki nilai bilangan bualat dengan menggunakan 'df.select_dtypes(include='int').columns.tolist()' dan hasilnya bisa dilihat seperti dibawah dan saya akan mengambil satu atribut yaitu humidity untuk dijadikan bilangan null nantinya

In [12]:
df = pd.read_csv('IndianWeatherRepository.csv')
kolom_bilangan_bulat = df.select_dtypes(include='int').columns.tolist()

print(kolom_bilangan_bulat)

['last_updated_epoch', 'wind_degree', 'humidity', 'cloud', 'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'moon_illumination']

    14. untuk lebih memastikannya saya menggunakan perintah 'print(df['humidity'].head())' dan terbukti bahwa atribut humidity memiliki nilai bilangan bulat.

In [13]:
print(df['humidity'].head())

0    67
1    70
2    70
3    76
4    74
Name: humidity, dtype: int64

    15 pada perintah dibawah saya mengubah beberapa kolom menjadi nilai null karena dataset saya tidak memiliki nilai null didalamnya.yang pertama seperti biasa kita memanggil library pamdasnya untuk membaca file.csv kita.

    a) terlihat saya menggunakan variable persentase_null,persentase_null2 dan persentase null3 untuk memberikan paramete berapa persen dari data dari atribut tersebut yang akan dijadikan null dan disini saya menggunakan angka '1' yang berarti label dari setiap atribut tersebut 100% dirubah menjadi null,

    b) disini saya menggunakan dungsi len(df) untuk mengembalikan nilai panjang data ke dalam dataframe df dan juga menggunakan fungsi loc() untuk mengakses setiap kolom dan menggantinya dengan nilai null.

In [18]:
import pandas as pd
import numpy as np


df = pd.read_csv('IndianWeatherRepository.csv')

persentase_null = 1 
persentase_null2 = 1 
persentase_null3 = 1 


jumlah_null1 = int(persentase_null * len(df))
jumlah_null2 = int(persentase_null2 * len(df))
jumlah_null3 = int(persentase_null3 * len(df))





indeks_null1 = np.random.choice(len(df), jumlah_null1, replace=False)
indeks_null2 = np.random.choice(len(df), jumlah_null2, replace=False)
indeks_null3 = np.random.choice(len(df), jumlah_null3, replace=False)


df.loc[jumlah_null1, 'temperature_celsius'] = np.nan

df.loc[jumlah_null2, 'location_name'] = np.nan

df.loc[jumlah_null3, 'humidity'] = np.nan

    16.seperti yang terlihat dalam 3 atribut diats telah berubah menjadi nilai null

In [76]:
df.head(20)

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,India,NaN,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,81.5,...,12.6,18.5,1,2,05:59 AM,06:41 PM,05:42 PM,03:38 AM,Waxing Gibbous,93
1,India,NaN,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,81.5,...,10.7,14.2,1,1,06:00 AM,06:40 PM,05:39 PM,03:41 AM,Waxing Gibbous,93
2,India,NaN,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,79.3,...,16.8,20.7,2,2,05:56 AM,06:34 PM,05:32 PM,03:39 AM,Waxing Gibbous,93
3,India,NaN,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,78.1,...,4.9,6.6,1,1,06:00 AM,06:38 PM,05:36 PM,03:43 AM,Waxing Gibbous,93
4,India,NaN,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,81.0,...,11.4,14.8,1,1,06:01 AM,06:39 PM,05:38 PM,03:42 AM,Waxing Gibbous,93
5,India,NaN,Madhya Pradesh,23.20,77.08,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,78.6,...,7.9,10.5,1,1,06:03 AM,06:42 PM,05:42 PM,03:44 AM,Waxing Gibbous,93
6,India,NaN,Madhya Pradesh,23.17,79.95,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,82.4,...,17.1,23.1,2,2,05:51 AM,06:31 PM,05:30 PM,03:32 AM,Waxing Gibbous,93
7,India,NaN,Madhya Pradesh,22.95,79.20,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,81.9,...,17.3,23.7,2,2,05:55 AM,06:34 PM,05:33 PM,03:36 AM,Waxing Gibbous,93
8,India,NaN,Madhya Pradesh,24.72,80.20,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,86.0,...,27.4,35.5,2,3,05:49 AM,06:31 PM,05:32 PM,03:27 AM,Waxing Gibbous,93
9,India,NaN,Madhya Pradesh,23.18,75.77,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,78.8,...,5.7,7.6,1,1,06:08 AM,06:48 PM,05:47 PM,03:49 AM,Waxing Gibbous,93
10,India,NaN,Madhya Pradesh,24.53,81.30,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,87.1,...,21.9,26.8,2,2,05:45 AM,06:26 PM,05:27 PM,03:23 AM,Waxing Gibbous,93
11,India,NaN,Madhya Pradesh,22.95,81.08,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,86.5,...,12.5,15.6,1,2,05:47 AM,06:26 PM,05:25 PM,03:28 AM,Waxing Gibbous,93
12,India,NaN,Madhya Pradesh,21.78,80.25,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,82.9,...,15.9,20.7,2,2,05:51 AM,06:28 PM,05:26 PM,03:34 AM,Waxing Gibbous,93
13,India,NaN,Madhya Pradesh,22.03,74.90,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,81.0,...,6.2,8.2,1,1,06:12 AM,06:50 PM,05:49 PM,03:55 AM,Waxing Gibbous,93
14,India,NaN,Madhya Pradesh,24.58,80.83,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,86.2,...,19.3,24.2,2,2,05:47 AM,06:28 PM,05:29 PM,03:25 AM,Waxing Gibbous,93
15,India,NaN,Madhya Pradesh,24.90,79.60,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,86.0,...,27.4,35.5,2,3,05:51 AM,06:34 PM,05:35 PM,03:29 AM,Waxing Gibbous,93
16,India,NaN,Madhya Pradesh,22.72,75.83,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,78.8,...,6.2,8.0,1,1,06:08 AM,06:47 PM,05:46 PM,03:50 AM,Waxing Gibbous,93
17,India,NaN,Madhya Pradesh,23.32,75.07,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,79.7,...,8.0,10.8,1,1,06:10 AM,06:51 PM,05:50 PM,03:52 AM,Waxing Gibbous,93
18,India,NaN,Madhya Pradesh,22.33,77.10,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,83.1,...,6.8,9.4,1,1,06:03 AM,06:42 PM,05:40 PM,03:46 AM,Waxing Gibbous,93
19,India,NaN,Madhya Pradesh,23.83,78.72,Asia/Kolkata,1693286100,2023-08-29 10:45,NaN,80.4,...,18.5,25.5,2,2,05:56 AM,06:36 PM,05:36 PM,03:36 AM,Waxing Gibbous,93

    17. karena atribut humidity tidak terlihat jadi saya meliaht datanya dengan fungsi head seperti dibawah dan terbukti telah berubah menjadi nilai null.

In [16]:
print(df['humidity'].head())

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: humidity, dtype: float64

    18. untuk merubah nilai null kedalam median,mean dan modus.pada kolom temperatur_celcius saya menggunaka fungsi mean()untuk menghitung rata-rata nilai dalam satu lokasi/modus pada data lokasi yang sering muncul dalam satu waktu dan menggunakan median() atau nilai tengah dalam humidity berdasarkan data yang sering muncul pada location_name  dan setelah di cetak hasilnya data yang sering muncul pada location_name adalah udaipur dengan rata-rata nilai temperature_celciusnya adalah 26.03 dan nilai tengah pada humidity adalah 70.50

In [17]:
df = pd.read_csv('IndianWeatherRepository.csv')

most_frequent_location = df['location_name'].mode()[0]
rata2_suhu = df[df['location_name'] == most_frequent_location]['temperature_celsius'].mean()


rata2_humidity = df[df['location_name'] == most_frequent_location]['humidity'].median()


print(f'Mean temperature_celsius for most frequent location ({most_frequent_location}): {rata2_suhu:.2f}')
print(f'Median humidity for most frequent location ({most_frequent_location}): {rata2_humidity:.2f}')

Mean temperature_celsius for most frequent location (Udaipur): 26.03
Median humidity for most frequent location (Udaipur): 70.50

### Data Cleaning Nilai Duplikat

    19. pertama kali kita mengecheck nilai duplikat yang berada di dalam dataset kita dengan menggunakan df.duplicated().sum() dan hasilnya adalah 0

In [18]:
df.duplicated().sum()

0

    20. selanjutnya kita kaan membuat nilai duplikatnya pada data pertama kita yaitu pada index 0. contohnya tambah_duplikat = df.iloc[0] dan melakukan deuplikat dengan menggunakan fungsi  append() pada df = df.append(tambah_duplikat, ignore_index=True)

In [19]:


tambah_duplikat = df.iloc[0]


df = df.append(tambah_duplikat, ignore_index=True)

C:\Users\iswan\AppData\Local\Temp\ipykernel_9596\4232868633.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(tambah_duplikat, ignore_index=True)

    21.ini adalah cara untuk melihat nilai duplikatnya seperti dibawah ini

In [20]:
duplikat_rows = df[df.duplicated(keep=False)]


print("Baris yang merupakan duplikat:")
print(duplikat_rows)

Baris yang merupakan duplikat:
      country location_name          region  latitude  longitude  \
0       India    Ashoknagar  Madhya Pradesh     24.57      77.72
17511   India    Ashoknagar  Madhya Pradesh     24.57      77.72

           timezone  last_updated_epoch      last_updated  \
0      Asia/Kolkata          1693286100  2023-08-29 10:45
17511  Asia/Kolkata          1693286100  2023-08-29 10:45

       temperature_celsius  temperature_fahrenheit  ... air_quality_PM2.5  \
0                     27.5                    81.5  ...              12.6
17511                 27.5                    81.5  ...              12.6

       air_quality_PM10  air_quality_us-epa-index  air_quality_gb-defra-index  \
0                  18.5                         1                           2
17511              18.5                         1                           2

        sunrise    sunset  moonrise   moonset      moon_phase  \
0      05:59 AM  06:41 PM  05:42 PM  03:38 AM  Waxing Gibbous
17511  05:59 AM  06:41 PM  05:42 PM  03:38 AM  Waxing Gibbous

       moon_illumination
0                     93
17511                 93

[2 rows x 42 columns]

    22. jika kurang puas kita dapat menggunakan df.duplicated().sum() seperti dibawah ini untuk melihat nilai duplikatnya dan ternyata ada 1 nilai yang duplikat.

In [21]:
df.duplicated().sum()

1

    23. selanjutnya kita gunakan fungsi drop() untuk menghapus nilai yang duplikat tersebut seperti dibawah ini

In [41]:
df.drop_duplicates(inplace=True)
print("\nSetelah menggunakan fungsi drop_duplicates()")
print("Jumlah nilai Duplikat:", df.duplicated().sum())

Setelah menggunakan fungsi drop_duplicates()
Jumlah nilai Duplikat: 0

### encoding

    24. untuk melakukan ordinal encoding dan dan one-hot-encoding kita mengimport terlebih dahulu library yang dibutuhkan seperti from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder karan padas sudah diimport terlebih dahulu diatas jadi kita tidak perlu lagi untuk mengimportnya untuk membaca file.csv kita.

In [42]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
df = pd.read_csv('IndianWeatherRepository.csv')

    25. untuk mengganti tipe data pada atribut latitude kita menggunakan astype untuk merubahnya ke tipe data integer dari yang awalnya adalah tipe data  float,seperti yang terlihat dalam output diatas

In [43]:


df['latitude'] = df['latitude'].astype(int)


df.to_csv('IndianWeatherRepository_updated.csv', index=False)

In [46]:
df

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,India,Ashoknagar,Madhya Pradesh,24,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,12.6,18.5,1,2,05:59 AM,06:41 PM,05:42 PM,03:38 AM,Waxing Gibbous,93
1,India,Raisen,Madhya Pradesh,23,77.80,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,10.7,14.2,1,1,06:00 AM,06:40 PM,05:39 PM,03:41 AM,Waxing Gibbous,93
2,India,Chhindwara,Madhya Pradesh,22,78.93,Asia/Kolkata,1693286100,2023-08-29 10:45,26.3,79.3,...,16.8,20.7,2,2,05:56 AM,06:34 PM,05:32 PM,03:39 AM,Waxing Gibbous,93
3,India,Betul,Madhya Pradesh,21,77.93,Asia/Kolkata,1693286100,2023-08-29 10:45,25.6,78.1,...,4.9,6.6,1,1,06:00 AM,06:38 PM,05:36 PM,03:43 AM,Waxing Gibbous,93
4,India,Hoshangabad,Madhya Pradesh,22,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.2,81.0,...,11.4,14.8,1,1,06:01 AM,06:39 PM,05:38 PM,03:42 AM,Waxing Gibbous,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17506,India,Niwari,Uttar Pradesh,28,77.53,Asia/Kolkata,1695941100,2023-09-29 04:15,25.0,77.0,...,148.7,238.7,4,10,06:11 AM,06:10 PM,05:42 PM,04:40 AM,Waxing Gibbous,97
17507,India,Saitual,Mizoram,23,92.58,Asia/Kolkata,1695941100,2023-09-29 04:15,22.7,72.9,...,12.3,12.8,1,2,05:10 AM,05:11 PM,04:37 PM,03:41 AM,Waxing Gibbous,97
17508,India,Ranipet,Tamil Nadu,12,79.33,Asia/Kolkata,1695941100,2023-09-29 04:15,25.0,77.0,...,8.7,11.2,1,1,06:02 AM,06:05 PM,05:27 PM,04:45 AM,Waxing Gibbous,97
17509,India,Tenkasi,Tamil Nadu,8,77.30,Asia/Kolkata,1695941100,2023-09-29 04:15,23.1,73.7,...,3.8,4.5,1,1,06:09 AM,06:13 PM,05:33 PM,04:56 AM,Waxing Gibbous,97
17510,India,Pendra,Maharashtra,21,74.15,Asia/Kolkata,1695941100,2023-09-29 04:15,22.9,73.2,...,40.0,43.4,2,4,06:23 AM,06:24 PM,05:52 PM,05:00 AM,Waxing Gibbous,97

    26.untuk melakukan one-hot-encoding saya menambhakn atribut baru ke dalam dataframe saya dengan nama waktu_hari dan meanbahkan nilai siang dan malam pada labelnya. untuk melakukannya saya menggunakan 'waktu_hari_values = np.random.choice(['siang', 'malam'], size=len(df), p=[0.5, 0.5])' dalam hal ini saya menmbahkan 50% pada siang dan 50% pada malam untuk nilai dalam labelnya.dan memasukkannya kedalam dataframe.

In [93]:
import pandas as pd
import numpy as np


df = pd.read_csv('IndianWeatherRepository.csv')


waktu_hari_values = np.random.choice(['siang', 'malam'], size=len(df), p=[0.5, 0.5])

df['waktu_hari'] = waktu_hari_values


print("DataFrame setelah menambahkan atribut 'waktu_hari':")
print(df.head())


df.to_csv('IndianWeatherRepository.csv', index=False)

DataFrame setelah menambahkan atribut 'waktu_hari':
  country location_name          region  latitude  longitude      timezone  \
0   India    Ashoknagar  Madhya Pradesh     24.57      77.72  Asia/Kolkata
1   India        Raisen  Madhya Pradesh     23.33      77.80  Asia/Kolkata
2   India    Chhindwara  Madhya Pradesh     22.07      78.93  Asia/Kolkata
3   India         Betul  Madhya Pradesh     21.86      77.93  Asia/Kolkata
4   India   Hoshangabad  Madhya Pradesh     22.75      77.72  Asia/Kolkata

   last_updated_epoch      last_updated  temperature_celsius  \
0          1693286100  2023-08-29 10:45                 27.5
1          1693286100  2023-08-29 10:45                 27.5
2          1693286100  2023-08-29 10:45                 26.3
3          1693286100  2023-08-29 10:45                 25.6
4          1693286100  2023-08-29 10:45                 27.2

   temperature_fahrenheit  ... air_quality_PM10  air_quality_us-epa-index  \
0                    81.5  ...             18.5                         1
1                    81.5  ...             14.2                         1
2                    79.3  ...             20.7                         2
3                    78.1  ...              6.6                         1
4                    81.0  ...             14.8                         1

   air_quality_gb-defra-index   sunrise    sunset  moonrise   moonset  \
0                           2  05:59 AM  06:41 PM  05:42 PM  03:38 AM
1                           1  06:00 AM  06:40 PM  05:39 PM  03:41 AM
2                           2  05:56 AM  06:34 PM  05:32 PM  03:39 AM
3                           1  06:00 AM  06:38 PM  05:36 PM  03:43 AM
4                           1  06:01 AM  06:39 PM  05:38 PM  03:42 AM

       moon_phase  moon_illumination  waktu_hari
0  Waxing Gibbous                 93       siang
1  Waxing Gibbous                 93       malam
2  Waxing Gibbous                 93       siang
3  Waxing Gibbous                 93       siang
4  Waxing Gibbous                 93       siang

[5 rows x 43 columns]

In [94]:
df.head(10)

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,waktu_hari
0,India,Ashoknagar,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,18.5,1,2,05:59 AM,06:41 PM,05:42 PM,03:38 AM,Waxing Gibbous,93,siang
1,India,Raisen,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,14.2,1,1,06:00 AM,06:40 PM,05:39 PM,03:41 AM,Waxing Gibbous,93,malam
2,India,Chhindwara,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,2023-08-29 10:45,26.3,79.3,...,20.7,2,2,05:56 AM,06:34 PM,05:32 PM,03:39 AM,Waxing Gibbous,93,siang
3,India,Betul,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,2023-08-29 10:45,25.6,78.1,...,6.6,1,1,06:00 AM,06:38 PM,05:36 PM,03:43 AM,Waxing Gibbous,93,siang
4,India,Hoshangabad,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.2,81.0,...,14.8,1,1,06:01 AM,06:39 PM,05:38 PM,03:42 AM,Waxing Gibbous,93,siang
5,India,Sehore,Madhya Pradesh,23.20,77.08,Asia/Kolkata,1693286100,2023-08-29 10:45,25.9,78.6,...,10.5,1,1,06:03 AM,06:42 PM,05:42 PM,03:44 AM,Waxing Gibbous,93,malam
6,India,Jabalpur,Madhya Pradesh,23.17,79.95,Asia/Kolkata,1693286100,2023-08-29 10:45,28.0,82.4,...,23.1,2,2,05:51 AM,06:31 PM,05:30 PM,03:32 AM,Waxing Gibbous,93,malam
7,India,Narsimhapur,Madhya Pradesh,22.95,79.20,Asia/Kolkata,1693286100,2023-08-29 10:45,27.7,81.9,...,23.7,2,2,05:55 AM,06:34 PM,05:33 PM,03:36 AM,Waxing Gibbous,93,siang
8,India,Panna,Madhya Pradesh,24.72,80.20,Asia/Kolkata,1693286100,2023-08-29 10:45,30.0,86.0,...,35.5,2,3,05:49 AM,06:31 PM,05:32 PM,03:27 AM,Waxing Gibbous,93,malam
9,India,Ujjain,Madhya Pradesh,23.18,75.77,Asia/Kolkata,1693286100,2023-08-29 10:45,26.0,78.8,...,7.6,1,1,06:08 AM,06:48 PM,05:47 PM,03:49 AM,Waxing Gibbous,93,siang

    27. pertama kita mengimport terlebih dahulu atribut yang diperlukan untuk melakukan one-hot=incoding yaitu 'from sklearn.preprocessing import OneHotEncoder'.dimana pada dataframe kita menginisialisasi 'OneHotEncoder = OneHotEncoder(sparse=False)' terlebih dahulu dan memilih atribut mana yang akan kita one-hot dan disini saya memilih data yang sudah saya buat sebelumnya yaitu waktu_hari,dan menyimpan data kedalam variable SexEnc

In [96]:
from sklearn.preprocessing import OneHotEncoder
df = pd.read_csv('IndianWeatherRepository.csv')
OneHotEncoder = OneHotEncoder(sparse=False)
SexEnc = OneHotEncoder.fit_transform(df[["waktu_hari"]])
SexEnc = pd.DataFrame(SexEnc)
df["siang"] = SexEnc[0]
df["malam"] = SexEnc[1]
df.head()

c:\Users\iswan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,waktu_hari,siang,malam
0,India,Ashoknagar,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,2,05:59 AM,06:41 PM,05:42 PM,03:38 AM,Waxing Gibbous,93,siang,0.0,1.0
1,India,Raisen,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,1,06:00 AM,06:40 PM,05:39 PM,03:41 AM,Waxing Gibbous,93,malam,1.0,0.0
2,India,Chhindwara,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,2023-08-29 10:45,26.3,79.3,...,2,05:56 AM,06:34 PM,05:32 PM,03:39 AM,Waxing Gibbous,93,siang,0.0,1.0
3,India,Betul,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,2023-08-29 10:45,25.6,78.1,...,1,06:00 AM,06:38 PM,05:36 PM,03:43 AM,Waxing Gibbous,93,siang,0.0,1.0
4,India,Hoshangabad,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.2,81.0,...,1,06:01 AM,06:39 PM,05:38 PM,03:42 AM,Waxing Gibbous,93,siang,0.0,1.0